#!/bin/bash
# Camette Button Manager
# Basic infinite loop for Button and LED checking on GPIO

SNAPSHOTPATH=/var/www/snapshots/
TIMELAPSEPATH=/var/www/timelapse_movies/quickbuttontimelapse/
SOUNDPATH=/var/www/recordedsounds/
TIMELAPSERUNNING=0
RECORDINGSOUND=0

# Port 21 == LED audio rec
echo "27" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio27/direction

#configure button
echo "4" > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio4/direction
echo "17" > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio17/direction
echo "22" > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio22/direction

echo "1" > /sys/class/gpio/gpio27/value
sleep 1
echo "0" > /sys/class/gpio/gpio27/value

BUTTON1=$(cat /sys/class/gpio/gpio4/value)
BUTTON2=$(cat /sys/class/gpio/gpio17/value)
BUTTON3=$(cat /sys/class/gpio/gpio22/value)

while [ true ]
do
# wait for a button to be pressed
while [ "$BUTTON1" == "1" -a "$BUTTON2" == "1" -a "$BUTTON3" == "1" ]
do
	sleep 0.1
	BUTTON1=$(cat /sys/class/gpio/gpio4/value)
	BUTTON2=$(cat /sys/class/gpio/gpio17/value)
	BUTTON3=$(cat /sys/class/gpio/gpio22/value)

done

# BUTTON1 == take a snapshot in full resolution
if [ "$BUTTON1" == "0" ]; then
	#raspistill -w 2592 -h 1944 -q 100 -o "$SNAPSHOTPATH"/snapshot$(date "+%d%H%M%S").jpg
# Take 49fps video
	raspivid -w 1296 -h 730 -fps 49 -t 18000000 -o "$SNAPSHOTPATH"/video49$(date "+%d%H%M%S").h264


#    2592×1944 1-15fps, video or stills mode, Full sensor full FOV, default stills capture
#    1920×1080 1-30fps, video mode, 1080p30 cropped
#    1296×972 1-42fps, video mode, 4:3 aspect binned full FOV. Used for stills preview in raspistill.
#    1296×730 1-49fps, video mode, 16:9 aspect , binned, full FOV (width), used for 720p
#    640×480 42.1-60fps, video mode, up to VGAp60 binned
#    640×480 60.1-90fps, video mode, up to VGAp90 binned

fi

# BUTTON2 == make a timelapse
if [ "$BUTTON2" == "0" ]; then
	case "$TIMELAPSERUNNING" in
	0 )
		if [ ! -d "$TIMELAPSEPATH" ]; then
			mkdir $TIMELAPSEPATH
		fi
		
		TIMELAPSERUNNING=1
        	raspistill -w 1920 -h 1080 -q 100 -tl 3000 -t 14400000 -o "$TIMELAPSEPATH"/$(date "+%d%H%M%S")_%04d.jpg &
	;;

	1 )
		kill -9 $(ps aux |grep "raspistill" | awk '{print $2}' |head -1)
		TIMELAPSERUNNING=0
	;;
	esac

fi

# BUTTON3 == record sound
if [ "$BUTTON3" == "0" ]; then
        case "$RECORDINGSOUND" in
        0 )
                if [ ! -d "$SOUNDPATH" ]; then
                        mkdir $SOUNDPATH
                fi

		SOUNDDEVICE=$(arecord -l |grep GoMic |awk '{print $3}')

		if [ "$SOUNDDEVICE" == "" ]; then
			echo "No recording device found"
		else
			echo "1" > /sys/class/gpio/gpio27/value
			arecord -D plughw:1 -f cd "$SOUNDPATH"/record$(date "+%d%H%M%S").wav &
                	RECORDINGSOUND=1
		fi
		
        ;;

        1 )
                kill $(ps aux |grep "arecord" | awk '{print $2}' |head -1)
                RECORDINGSOUND=0
		echo "0" > /sys/class/gpio/gpio27/value
        ;;
        esac

fi

sleep 2

BUTTON1=$(cat /sys/class/gpio/gpio4/value)
BUTTON2=$(cat /sys/class/gpio/gpio17/value)
BUTTON3=$(cat /sys/class/gpio/gpio22/value)


done

#echo "1" > /sys/class/gpio/gpio27/value

#cat /sys/class/gpio/gpio4/value 
#cat /sys/class/gpio/gpio17/value
#cat /sys/class/gpio/gpio22/value

#sleep 1

#echo "0" > /sys/class/gpio/gpio27/value

echo "27" > /sys/class/gpio/unexport
echo "4" > /sys/class/gpio/unexport
echo "17" > /sys/class/gpio/unexport
echo "22" > /sys/class/gpio/unexport
